### ISSUE TITLE
"4041: Launch 'None' not found. Did you use correct Launch ID?"

### ISSUE THREAD

**Issue by senegal8green** [Adrian-Tamas/reportportal-behave-integration-client-lib#1]
Hi @Adrian-Tamas ! Could you please help or clarify one point.
Using your lib while running behave scenarious i get the next error in console Message : <class 'reportportal_client.errors.ResponseError'>Arguments: (ResponseError("4041: Launch 'None' not found. Did you use correct Launch ID?"). So i do not know what to do with it.
Have you any idea  please about how it can be solved?

**Comment by dunossauro** [comment]
This error is related to Report portal Python-client.

Today I opened this issue: https://github.com/reportportal/client-Python/issues/53

**Comment by dunossauro** [comment]
@senegal8green, the download official version is the version 5.0 (BETA). You download recently?

**Comment by senegal8green** [comment]
@dunossauro  thanks buddy, but i am not sure i got your point about versions because as i can see i am using the last version of reportportal-client and it is 3.2.0 (installed using pip) How i can download the 4.0 version could you please explain?

**Comment by dunossauro** [comment]
@senegal8green, Sorry, for my explanation. The beta version is from report portal.

When you downloaded from reportportal.io and no parametrize nothing, they download the beta version and the reportportal python client don't support this version yet.

**Comment by Adrian-Tamas** [comment]
Hi @senegal8green, sorry for the late response. When I created this lib I was using:
reportportal-behave-client            1.0.1
reportportal-client                   3.2.0

And the ReportPortal version used was 4.3. I have not tried with the latest 5.0 beta version from here: https://github.com/reportportal/reportportal/releases and I can't try at this time with that because I needed to move to VirtualBox on Windows for other stuff.

**Comment by dunossauro** [comment]
Hi @ Adrian-Tamas, API version 5.0 has a new semantical version  `v1`. It's weird to me. because they don't support, I don't know, version 0 of the API. But this problem is related to `reportportal-client`. The library is maintained by the reportportal team.

Maybe in the future reportportal team update the library.

**Comment by Adrian-Tamas** [comment]
I have just released v1.0.3 of the lib which has been updated to work with Report Portal v5.1 and reportportal-client > 5.0.3. You know need to keep track of the run ids for the launch, steps, scenarios and features. The readme has been updated to reflect how this is supposed to work
